name: Build wheels

on:
  push:
    tags:
    - '*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    permissions:
      id-token: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_TEST_REQUIRES: tox
          CIBW_TEST_COMMAND: cd {project} && tox
          CIBW_TEST_SKIP: "*-win*"
          CIBW_BUILD_VERBOSITY: 1

      - name: Release to pypi
        uses: pypa/gh-action-pypi-publish@release/v1

  build_wheels_aarch64:
    name: Build wheels on ${{ matrix.os }}
    # permissions:
      # id-token: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, windows-11-arm]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel twine

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist

      # - name: Release to pypi
      #   uses: pypa/gh-action-pypi-publish@release/v1

      # pypa/gh-action-pypi-publish does not have arm support yet
      # use twine for now
      - name: Release to pypi
        run: python -m twine upload dist/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

  build_source:
    name: Build source distribution
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install setuptools

      - name: Build source distribution
        run: python setup.py sdist

      - name: Release to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
